SELECT a.TITLE, 
    b.BOARD_ID, 
    b.REPLY_ID, 
    b.WRITER_ID, 
    b.CONTENTS, 
    DATE_FORMAT(b.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD a JOIN USED_GOODS_REPLY b
ON a.BOARD_ID = b.BOARD_ID
WHERE a.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE ASC, TITLE ASC