SELECT a.FLAVOR
FROM FIRST_HALF a JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) b
ON a.FLAVOR = b.FLAVOR
ORDER BY a.TOTAL_ORDER + b.TOTAL_ORDER DESC
LIMIT 3