SELECT a.PRODUCT_ID, a.PRODUCT_NAME, (a.PRICE * b.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT a JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) as AMOUNT
    FROM FOOD_ORDER 
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID) b
ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC